budget/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView
import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'budget.views.home', name='home'),
    # url(r'^budget/', include('budget.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'budgetapp.views.index', name='index'),
    (r'^index/$', 'budgetapp.views.index'),
    url(r'^uploadcsv/$', 'csvprocessor.views.uploadcsv', name='uploadcsv'),
    url(r'^fetch_transactions_ajax/$', 'csvprocessor.views.fetch_transactions', name='fetch_transactions_ajax'),
    (r'^fetch_transactions/$', TemplateView.as_view(template_name='fetch_transactions.html')),
    url(r'^addcategory/$', 'budgetapp.views.addcategory', name='addcategory'),
    url(r'^addpaycheck/$', 'budgetapp.views.addpaycheck', name='addpaycheck'),
    url(r'^excludepaycheck/$', 'budgetapp.views.excludepaycheck', name='excludepaycheck'),
    url(r'^addpurchase/$', 'budgetapp.views.addpurchase', name='addpurchase'),
    url(r'^getreport/$', 'budgetapp.views.getreport', name='getreport'),
    url(r'^getpurchasestable/$', 'budgetapp.views.getpurchasetable', name='getpurchasestable'),
    url(r'^get_budget_status/$', 'budgetapp.views.get_budget_status', name='get_budget_status'),
    url(r'^getpaycheckstable/$', 'budgetapp.views.getpaycheckstable', name='getpaycheckstable'),
    url(r'^getsubchart/$', 'budgetapp.views.getsubchart', name='getsubchart'),
)

budgetapp/forms.py
# -*- coding: utf-8 -*-
from django import forms
from models import SuperCategory, SubCategory, MyModelChoiceField
from django.forms import ModelChoiceField
from django.forms import widgets
import calendar
import datetime


MONTHS = [((calendar.month_name[month]), (calendar.month_name[month])) for month in range(1,13)]

YEARS = [(year, year) for year in range(2010, datetime.date.today().year+1)]

class AddCategoryForm(forms.Form):
    super_category  = forms.TextInput()
    sub_category = forms.CharField(widget=forms.TextInput(attrs={'maxlength':50}),)

    def get(self, request, *args, **kwargs):
        #todo throw exception here since you shouldn't get this
        pass

    def post(self, request, *args, **kwargs):
        print "something"



class AddPaycheckForm(forms.Form):
    month  = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ('mm'), 'maxlength':2, 'class':'month'}),)
    day  = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ('dd'), 'maxlength':2, 'class':'day'}),)
    year  = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ('yyyy'), 'maxlength':4, 'class':'year'}),)
    gross  = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ('gross'), 'maxlength':'8'}),)
    tax  = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ('tax'), 'maxlength':'8'}),)
    k401  = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ('k401'), 'maxlength':'8'}),)
    healthcare  = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ('healthcare'), 'maxlength':'8'}),)
    fica  = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ('fica'), 'maxlength':'8'}),)

class AddPurchaseForm(forms.Form):
    month  = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ('mm'), 'maxlength':2, 'class':'month'}),)
    day  = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ('dd'), 'maxlength':2, 'class':'day'}),)
    year  = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ('yyyy'), 'maxlength':4, 'class':'year'}),)
    description  = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ('Description'), 'maxlength':'8', 'class':'description'}),)
    category  = forms.ModelChoiceField(queryset=SubCategory.objects.order_by('superCategory__name'), empty_label="Select SubCategory")
    cost  = forms.CharField(widget=forms.TextInput(attrs={'placeholder': (''), 'maxlength':'8', 'class': 'cost'}),)


class NavigationForm(forms.Form):
    standard_month = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class': 'radio_switches', 'onClick': "getReport('standard')", 'id':'months'}), choices=MONTHS, required=False)
    standard_year = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class': 'radio_switches', 'onClick': "alert('hello world')", 'id':'years'}), choices=YEARS, required=False)
    custom_month  = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ('mm'), 'maxlength':2, 'class':'month'}), required=False)
    custom_day  = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ('dd'), 'maxlength':2, 'class':'day'}), required=False)
    custom_year  = forms.CharField(widget=forms.TextInput(attrs={'placeholder': ('yyyy'), 'maxlength':4, 'class':'year'}), required=False)

templates/add_paycheck.html
<div id="input_paycheck" class="input_paycheck">
    <form id="addpaycheck_form" method="post" action="{% url 'addpaycheck' %}" >
        <div style="display:inline; float:left">
            <label  for='id_month'><span>Date</span></label>
            <br>
            {{ input_paycheck.month }} / {{ input_paycheck.day }} / {{ input_paycheck.year }}
        </div>
        <div style="display:inline; float:left; margin-left:30px">
            <label  for='gross'><span>Gross Pay</span></label>
            <br>
            {{ input_paycheck.gross }}
        </div>

        <div style="display:inline; float:left; margin-left:30px">
            <label  for='tax'><span>Tax</span></label>
            <br>
            <span class='deduct_td'>-$</span>
            {{ input_paycheck.tax }}
        </div>

        <div style="display:inline; float:left; margin-left:30px">
            <label  for='k401'><span>401k</span></label>
            <br>
            <span class='deduct_td'>-$</span>
            {{ input_paycheck.k401 }}
        </div>

        <div style="display:inline; float:left; margin-left:30px">
            <label  for='healthcare'><span>Healthcare</span></label>
            <br>
            <span class='deduct_td'>-$</span>
            {{ input_paycheck.healthcare }}
        </div>

        <div style="display:inline; float:left; margin-left:30px">
            <label  for='fica'><span>FICA</span></label>
            <br>
            <span class='deduct_td'>-$</span>
            {{ input_paycheck.fica }}
        </div>

    </form>
</div>
<br>
<br>
<br>
<br>
<br>
<div><a class='button' onClick=addPaycheck() href='javascript:void(0);'><span>Add Paycheck</span></a></div>
<br>
<span id="addpaycheckresult"></span>

templates/budget_status.html
{% for key,value in budget_map.items %}
<div class="supercategory"><span id="{{ key }}">{{ key }}</span>
	{% for budget in value %}
   <div data-subcategory="{{budget.subcategory}}" class="progressLabel">
      <div class="title">{{ budget.subcategory }}</div>
      <div class="total">$<span id="{{ budget.subcategory }}_currentval">{{budget.spent}}</span> of $<span id="{{ budget.subcategory }}_maxval">{{ budget.budgeted }}</span></div>
   <div data-original="{{budget.original_estimate}}" data-max="{{ budget.budgeted }}" id="{{ budget.subcategory}}_progressbar" class="progressBar"><div></div></div>
   	
   </div>
   {% endfor %}
</div>
{% endfor %}

templates/getreport.html
<div id="reportResult" style=""><h3>Report for <span id="from_date"></span> to <span id="to_date"></span></h3></div>
<div id="finalSummaryDiv">
    INCOME:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <span id="income" class="income"></span>
    <br>
    EXPENSES:&nbsp;&nbsp;
    <span id="expenses" class="expenses"></span>
    <br>
    SAVINGS:&nbsp;&nbsp;&nbsp;&nbsp;
    <span id="savings" class="income"></span>
</div>
<br>
<br>
<br>
<div class="allreports" id="allreports" style="display: block;">

    <div  style="float: left;">
        <br>
        <div class="superChart" id="super_chart_div">
        </div>

        <br>

        <!--<div class="superChart" id="sub_chart_div" style="margin-top:-20px">
        </div>
        <br>
        <div class="superChart" id="bd_chart_div" style="margin-top:-20px">
        </div>-->

        <span class="subChart" id="sub_net_chart_div" style="display: none;">
        </span>

        <div class="caption" id="piechartsummary" style="width:200px; height:150px; margin-left:50px; margin-top:-75px;">
        </div>
    </div>

    <div style="display:inline-block">
        <br>
        <div class="" id="budgetTable">
            
        </div>
    </div>


    <br>
    <br>
    <br>
    <br>

    <div class="" id="purchasesTable2" style="clear: both">
    </div>
    <br>
    <br>
    <div class="" id="paycheckTable" style="">
    </div>
</div>

templates/index.html
{% load url from future %}
{% load less %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/superfish.css" media="screen">
    <link href="{{ STATIC_URL }}less/styles.less" type="text/less" rel="stylesheet">
    <!--<link rel="stylesheet" type="text/css" href="{{ STATIC_URL}}LESS_CACHE/less/styles-10c7edfc7061.css" />-->
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL}}css/compiled_css.css" />
    <title>Transactions</title>
</head>
<body>
    <h3>report budget</h3>

    <script type="text/javascript" src="http://code.jquery.com/jquery-1.4.3.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/hoverIntent.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/superfish.js"></script>
    <script type='text/javascript' src='http://www.datatables.net/release-datatables/media/js/jquery.dataTables.js'></script>
    <script type='text/javascript' src='https://www.google.com/jsapi'></script>
    <script type='text/javascript' src="{{ STATIC_URL }}js/budget.js"></script>
    <script type='text/javascript' src="{{ STATIC_URL }}js/report.js"></script>

    <script type='text/javascript'>
        jQuery(function(){
            jQuery('ul.sf-menu').superfish();
        });

        // Load the Visualization API and the piechart package.
        google.load('visualization', '1.0', {'packages':['corechart']});
        google.load('visualization', '1', {packages:['table']});
    </script>


    {% include "modals/addcategory.html" %}
    <div id="background_overlay"></div>

    {%  include "add_paycheck.html" %}

    <br>
    <br>

    {% include "input_receipt.html" %}

    <br>
    <br>

    {%  include "navigation.html" %}

    <br>
    <br>

    {%  include "getreport.html" %}

    <br>
    <br>
</body>
</html>

templates/input_receipt.html
<div class="input_receipt" id="input_receipt" style="height:100px">
    <form method="post"  action="{% url 'addpurchase' %}" enctype="application/x-www-form-urlencoded" id="receipt_form">
        <div class="product_table" id="product_table" style="display:inline; float:left; margin-left:30px;">
            <div id="label_div">

            </div>
            <div id="product_div_1" class="product_div">
                <span id="date_span_1" style="display:inline; float:left;">
                    <label for="month_1" class="product_label"><span>Date</span></label>
                    <div style="  height:50px;">
                        {{ add_purchase.month }} / {{ add_purchase.day }} / {{ add_purchase.year }}
                    </div>
                </span>
                <span id="description_span_1" style="display:inline; float:left; margin-left:10px">
                    <label for="description_1" class="product_label"><span>Item Description</span></label>
                    <div style="  height:50px">
                        {{ add_purchase.description }}
                    </div>
                </span>
                <span id="category_span_1" style="display:inline; float:left; margin-left:10px">
                    <label for="category_1" class="product_label"><span>Category</span></label>
                    <div style="  height:50px">
                        {{ add_purchase.category }}
                        <ul id="category_dropdown" class="sf-menu category_dropdown">
                            <li class="current category_dropdown">
                                <a class="category_dropdown main_dropdown" href="#a"><span class="category_content">Choose a category</span></a>
                                <ul class="category_dropdown">
                                {% for superCategory, subCategories in category_dict.items %}
                                    <li class="supercategory_li category_dropdown">
                                        <a class="category_dropdown supercategory"  href="#ab"><span class="category_content">{{ superCategory }}</span></a>
                                        <ul class="category_dropdown">
                                            {%  for subcategory in subCategories %}
                                                <li class="subcategory_li"><a class="category_dropdown subcategory" href="#">{{ subcategory }}</a></li>
                                            {%  endfor %}
                                                <li class="subcategory_li"><a class="category_dropdown subcategory" href="#">Add Category</a></li>
                                        </ul>
                                    </li>
                                {% endfor %}
                                </ul>
                            </li>
                        </ul>
                    </div>
                </span>
                <span id="cost_span_1" style="display:inline; float:left; margin-left:10px">
                    <label for="cost1" class="product_label"><span>Cost</span></label>
                    <div style=" height:50px">
                        {{ add_purchase.cost }}
                    </div>
                </span>
                <span class="addremove_td" id="add_span" style="display:inline; float:left; margin-left:10px">
                    <label for="add_1" class="product_label"><span>&nbsp;</span></label>
                    <div style="  height:50px">
                        <a name="add_1" onclick="addProduct()" href="javascript:void(0);" id="add_1"><img src="{{ STATIC_URL }}images/plus.jpg"></a>&nbsp;&nbsp;
                        <a name="remove_1" onclick="removeProduct(this.id)" href="javascript:void(0);" id="remove_1"><img src="{{ STATIC_URL }}images/minus.jpg"></a>
                    </div>
                </span>
            </div>
        </div>
        <br>
        <br>
        <br>
    </form>
</div>
<div>
    <a class="button" onclick="addReceipt()" href="javascript:void(0)"><span>Add Receipt</span></a><br>
    <br>
    <span id="addreceiptresult"></span>
</div>

templates/navigation.html
<div class="generate_report">
    <form method="post" action="{% url 'getreport' %}"  enctype="application/x-www-form-urlencoded" name="report_form" id="report_form">
        <p class="thelabel">
            Choose a monthly report
        </p>
        <p id="months_switch"  class="switch">
            {% for radio in navigation_form.standard_month %}
                {{ radio.tag }}
            {% endfor %}
            {% for i in months %}
                &nbsp;&nbsp;<label for="months_{{  forloop.counter0 }}" id="cb-{{ forloop.counter0 }}" class="cb-enable"><span>{{ i }}</span></label>
                <!-- &nbsp;&nbsp;<input onclick="getReport('standard')" type="radio" class="radio_switches checkbox" id="{#   i  #}" name="{# i #}" value="{# i #}"> -->
            {% endfor %}
        </p>
        <br>
        <p id="years_switch" class="switch">
            {% for radio in navigation_form.standard_year %}

                {# radio.tag #}
            {% endfor %}
            {% for i in years %}
                &nbsp;&nbsp;<label id="cb-{{ i  }}" for="years_{{ i}}" class="cb-enable"><span>{{ i }}</span></label>
                <!-- <input onclick="getReport('standard')" type="radio" class="radio_switches" id="{# i #}" name="{# i #}" value="{# i #}">-->
                <input onclick="getReport('standard')" type="radio" class="radio_switches" id="years_{{ i }}" name="years_{{ i }}" value="{{ i }}">
            {% endfor %}
        </p><br>
        <br>
        <p class="thelabel">
            Or, define your own custom date
        </p>
        <input type="text" name="Date" value="mm" size="1" maxlength="2" id="frommonth">/<input type="text" name="Date" value="dd" size="1" maxlength="2" id="fromday">/<input type="text" name="Date" value="yyyy" size="2" maxlength="4" id="fromyear"> to
        <input type="text" name="Date" value="mm" size="1" maxlength="2" id="tomonth">/<input type="text" name="Date" value="dd" size="1" maxlength="2" id="today">/<input type="text" name="Date" value="yyyy" size="2" maxlength="4" id="toyear"><br>
        <br>
        <a class="button" onclick="getReport('custom')" href="javascript:void(0)"><span>Go!</span></a>
        <br>
        <br>
        <br>
        <p class="thelabel">
            Transactions out of date?
        </p>
        <a id="fetch_button" class="button" onclick="getTransactions()" href="javascript:void(0)"><span>Fetch Transactions</span></a>
        <a id="spinner_button" class="button" style="background-color:#ffffff; height:35px; width:177px; display:none; background-repeat:no-repeat; background-position:center; background-image:url('http://www.mytreedb.com/uploads/mytreedb/loader/ajax_loader_blue_32.gif')" href="javascript:void(0)"><span></span></a>
    </form>
</div>

templates/paychecks_table.html
{% load purchase_tags %}

<table cellpadding="0" cellspacing="0" border="0" class="purchases_table" id="paychecks_table">
    <thead>
        <tr>
            <th class="date">Date</th>
            <th class="gross">Gross</th>
            <th class="deductions">Tax</th>
            <th class="deductions">Healthcare</th>
            <th class="deductions">FICA</th>
            <th class="deductions">401K</th>
            <th class="total_deducts">Deductions</th>
            <th class="net">Net</th>
            <th class="excluded">Exclude?</th>
        </tr>
    </thead>
    <tbody>
        {% for paycheck in paychecks_list %}
            <tr>
                <td class="date">{{ paycheck.date }}</td>
                <td class="gross">{{ paycheck.gross|currency }}</td>
                <td class="deductions">{{ paycheck.tax|currency }}</td>
                <td class="deductions">{{ paycheck.healthcare|currency }}</td>
                <td class="deductions">{{ paycheck.fica|currency }}</td>
                <td class="deductions">{{ paycheck.k401|currency }}</td>
                <td class="deductions">{{ paycheck.total_deductions|currency }}</td>
                <td class="net">{{ paycheck.net|currency }}</td>
                <td class="excluded {% if paycheck.excluded %}excludedPaycheck{% endif %}"><input data-pk="{{ paycheck.pk }}" data-action="{% url 'excludepaycheck' %}" {% if paycheck.excluded %}checked{% endif %} type="checkbox" onchange="excludePaycheck(this)" /></td>
            </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <th class="date" style="text-align:right">Totals:</th>
            <th class="gross"></th>
            <th class="deductions"></th>
            <th class="deductions"></th>
            <th class="deductions"></th>
            <th class="deductions"></th>
            <th class="total_deducts"></th>
            <th class="net"></th>
        </tr>
    </tfoot>
</table>

templates/purchases_table.html
{% load purchase_tags %}

<table cellpadding="0" cellspacing="0" border="0" class="purchases_table" id="purchases_table">
    <thead> 
    <tr> 
        <th>Date</th> 
        <th>Description</th> 
        <th class="category">Category</th> 
        <th class="category">Sub-category</th> 
        <th>Cost</th> 
        </tr> 
    </thead> 
    <tbody>
        {% for transaction in transaction_list %}
            <tr>
               <td>{{ transaction.date }}</td>
               <td>{{ transaction.item_desc }}</td>
               <td class="category">{{ transaction.category.superCategory }}</td>
               <td class="category">{{ transaction.category.subCategory }}</td>
               {% if transaction.cost < 0 %}
                    <td class="income">
               {% else %}
                    <td>
                {% endif %}
                   {{ transaction.cost|currency }}
               </td>
            </tr>
        {% endfor %}
    </tbody> 
    <tfoot> 
        <tr>
            <th style="text-align:right" colspan="4">Total:</th>
            <th>{{ total }}</th>
        </tr>
    </tfoot>
</table>